[package]
name = "diagnostics"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2018"
repository= "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler framework for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../README.md"

[badges]
maintenance = { status = "actively-developed" }


[dependencies]

once_cell = "1.8.0"

linkme = "0.2.6"
paste = "1.0.5"

salsa = "0.17.0-pre.2"

data-structures = {version = "0.0.0", path = "../data_structures" }
macros = {version = "0.0.0", path = "../macros" }

syntax = {version = "0.0.0", path = "../syntax"}
basedb = {version = "0.0.0", path = "../basedb" }

[dependencies.annotate-snippets]
version = "0.9.0"
features = ["color"]


