[package]
name = "openvaf-session"
version = "0.7.0"
authors = ["DSPOM"]
edition = "2018"
repository= "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler framework for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../../README.md"

[badges]
maintenance = { status = "actively-developed" }


[dependencies]
linkme = "0.2"
paste = "1.0"
log = "0.4"
more-asserts = "0.2"
bytecount = "0.6"
bumpalo = "3.4"

openvaf-data-structures = {version = "0.7.0", path = "../data_structures" }
openvaf-macros = {version = "0.7.0", path = "../macros" }

