[package]
name = "openvaf-session"
version = "0.7.0"
authors = ["DSPOM"]
edition = "2018"
repository= "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler framework for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../README.md"

[badges]
maintenance = { status = "actively-developed" }


[dependencies]
linkme = "0.2"
paste = "1.0"
more-asserts = "0.2"
bytecount = "0.6"
bumpalo = "3.4"
tracing = "0.1"
tracing-error = "0.1"
openvaf-data-structures = {version = "0.7.0", path = "../data_structures" }
openvaf-macros = {version = "0.7.0", path = "../macros" }

serde = {version = "1.0", optional=true}
cfg-if = "1.0"

[features]

default = []

serde_dump = ["serde"]
global_session = ["openvaf-data-structures/threading"]