[package]
name = "openvaf-driver"
version = "0.1.1"
authors = ["DSPOM"]
edition = "2021"
license = "GPL-3.0"

[lib]
doctest = false

[[bin]]
name = "openvaf"
path = "src/main.rs"


[dependencies]

syntax = {version = "0.0.0", path = "../syntax"}
basedb = { version = "0.0.0", path = "../basedb" }
hir_def = { version = "0.0.0", path = "../hir_def" }
hir_lower = {version ="0.0.0", path ="../hir_lower"}
hir_ty = { version = "0.0.0", path = "../hir_ty" }

sim_back = { version = "0.0.0", path = "../sim_back" }
osdi = { version = "0.0.0", path = "../osdi" }
llvm = { version = "0.0.0", path = "../llvm" }
mir_llvm = { version = "0.0.0", path = "../mir_llvm" }

target = { version = "0.0.0", path = "../target" }
linker = { version = "0.0.0", path = "../linker" }

stdx = { version = "0.0.0", path = "../stdx" }
typed_indexmap = {version = "0.0.0", path = "../typed_indexmap"}
base_n = {version = "1", path = "../../lib/base_n"}
paths = {version = "0.0", path = "../paths"}

clap = "3.1.18"
lasso = {version = "0.6", features = ["ahash"]}
indexmap = "1.6"
md5 = "0.7"
directories-next = "2"
path-absolutize = "3.0.13"

smol_str = "0.1.22"
parking_lot = "0.12"
typed-index-collections = "3"
ahash = "0.7"

anyhow = "1"
termcolor = "1.1"

mimalloc = { version = "*", default-features = false }

