image: archlinux

packages:
  - rust
  - llvm
  - s3cmd
  - cbindgen
  - rust-bindgen

secrets:
  - a7b78c60-966c-46c7-a584-4a9ba3738fa0

environment:
  CI: 1
  RUST_BACK_TRACE: 1
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short


tasks:
  - pull_cache: |
        cd OpenVAF
        source ./.vendor/pull.sh
        cargo xtask cache fetch 

  - build: |
      cd OpenVAF
      cargo test --no-run 

  # immidietly push the cache so it gets saved even when the other tasks fail!
  
  - push_cache: |
      cd OpenVAF
      cargo xtask cache update

  - check_fmt: |
      cd OpenVAF
      cargo fmt --all -- --check
   
  - clippy: |
      cd OpenVAF
      cargo clippy -- -D warnings

  - test: | 
      cd OpenVAF
      cargo test



