default:
  image: 'rust:latest'
  cache: &global_cache
    key: ${CI_COMMIT_REF_SLUG}

    paths:
      - .cargo/
      - target/

stages:
  - build
  - test
  - doc


workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

build:
  stage: build
  script:
    - rustc --version
    - cargo --version
    - cargo update
    - cargo build --verbose
    
test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cd frontend
    - cargo test --verbose


test_fmt:
  stage: test

  before_script:
    - rustup component add rustfmt

  script:
    - cargo fmt -- --check

  cache:
    <<: *global_cache
    policy: pull



test_clippy:
  stage: test

  before_script:
    - rustup component add clippy

  script:
    - cargo clippy -- -D warnings




pages:
  image: "rustlang/rust:nightly"

  stage: doc
  script:
    - cargo doc --workspace --document-private-items
    - mkdir public
    - cp -R target/doc public/dev_doc
    - cargo doc --workspace
    - cp -R target/doc public/api_doc
    - echo '<meta http-equiv="refresh" content="0; url=open_vaf/index.html">' > public/api_doc/index.html
    - echo '<meta http-equiv="refresh" content="0; url=open_vaf/index.html">' > public/dev_doc/index.html

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


  cache:
    <<: *global_cache
    key: documentation


