default:
  image: 'rust:latest'
  cache: &global_cache
    key: ${CI_COMMIT_REF_SLUG}

    paths:
      - .cargo/
      - target/

stages:
  - build
  - test
  - doc

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt
  RUSTUP_HOME: $CI_PROJECT_DIR/rustup



build:
  stage: build
  script:
    - rustc --version
    - cargo --version
    - cargo build --verbose

  only:
    - master
    - merge_requests
    - tags

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cd frontend
    - cargo test --verbose

  only:
    - master
    - merge_requests
    - tags

test_fmt:
  stage: test

  before_script:
    - rustup component add rustfmt

  script:
    - cargo fmt -- --check

  only:
    - master
    - merge_requests
    - tags


test_clippy:
  stage: test

  before_script:
    - rustup component add clippy

  script:
    - cargo clippy -- -D warnings

  only:
    - master
    - merge_requests
    - tags


pages:
  stage: doc
  script:
    - cargo +nightly doc --workspace --document-private-items
    - cp -R target/doc docs/internal
    - cargo +nightly doc --workspace
    - cp -R target/doc docs/api
    - echo '<meta http-equiv="refresh" content="0; url=open_vaf/index.html">' > docs/internal/index.html
    - echo '<meta http-equiv="refresh" content="0; url=open_vaf/index.html">' > docs/api/index.html

  artifacts:
    paths:
      - docs
  only:
    - master

  cache:
    key: documentation
    <<: *global_cache


