
[workspace]
resolver = "2"
members = ["crates/*"]
exclude = ["crates/constants","crates/linker","crates/lld","crates/codegen_llvm","crates/pass","crates/middle","crates/targets","crates/const_eval","crates/data_flow"]

# [profile.dev]
# Disabling debug info speeds up builds a bunch,
# and we don't rely on it for debugging that much.
# debug = 0

[profile.dev.package]
# These speed up local tests.
rowan.opt-level = 3
rustc-hash.opt-level = 3
ahash.opt-level = 3
smol_str.opt-level = 3
text-size.opt-level = 3
# This speeds up `cargo xtask dist`.
# miniz_oxide.opt-level = 3
