[package]
name = "VARF"
version = "0.2.0"
authors = ["DSOM"]
edition = "2018"

[dependencies]
log="0.4.8"
intrusive-collections = "0.9.0"
logos = "0.10"
indexmap = "1.3.2"
ahash = "0.3.2"
lazy_static = "1.4.0"
copyless = "0.1.4"
bitflags = "1.2.1"
float-cmp = "0.6.0"
ansi_term = "0.12.1"
beef = "0.4.2"
rustc-hash = "1.1.0"
rustc-ap-graphviz = {version = "654.0.0",optional=true}

[dependencies.bytecount]
version = "0.6.0"
features = ["runtime-dispatch-simd"]

[dependencies.annotate-snippets]
version = "0.8.0"
features = ["color"]

[dependencies.bumpalo]
version = "3.2.1"
features=['collections']

#Logging for tests
[dev-dependencies]
criterion = "0.3.1"
fern={version="*",features=["colored"]}
chrono="*"
jemallocator-global = "*"



[[bench]]
name = "parser_bench"
harness = false


[features]

default = []

graph_debug = ["rustc-ap-graphviz"]

