[package]
name = "VARF"
version = "0.1.10"
authors = ["DSOM"]
edition = "2018"


[dependencies]
log="*"
intrusive-collections = "0.8.5"
logos = "0.10"
indexmap = "1.3.1"
ahash = "0.3.2"
lazy_static = "1.4.0"
copyless = "0.1.4"
bitflags = "1.2.1"
pretty = "0.9.0"
float-cmp = "0.6.0"
ansi_term = "0.12.1"



[dependencies.bytecount]
version = "0.6.0"
features = ["runtime-dispatch-simd"]

[dependencies.annotate-snippets]
version = "0.6.1"
features = ["ansi_term"]

[dependencies.bumpalo]
version = "3.1.2"
features=['collections']

#Logging for tests
[dev-dependencies]
criterion = "0.3.1"
fern={version="*",features=["colored"]}
chrono="*"
jemallocator-global = "*"
[profile.dev]
opt-level = 1

[[bench]]
name = "parser_bench"
harness = false
#[[test]]
#name = "parser_test"
#harness = true

