[package]
name = "adms_rust"
version = "0.1.0"
authors = ["DSOM"]
edition = "2018"

[dependencies]
pest = "*"
pest_derive = "*"
indextree = "*"
typed-arena = "*"
log = "*"
paste="*"
#jemallocator = "*"

#Logging for tests
#[dev-dependencies]
fern={version="*",features=["colored"]}
chrono="*"


