[package]
name = "adms_rust"
version = "0.1.0"
authors = ["DSOM"]
edition = "2018"

[dependencies]
pest = "*"
pest_derive = "*"
indextree = "*"
log = "*"
fern={version="*",features=["colored"]}
chrono="*"