[package]
name = "VARF"
version = "0.1.0"
authors = ["DSOM"]
edition = "2018"

[dependencies]
nom="*"
nom_locate = "*"
nom-trace = "*"
log="*"
intrusive-collections = "*"
logos = "*"

[dependencies.hesr_alloc]
path = "../im_he_sr_graph"

#Logging for tests
[dev-dependencies]
fern={version="*",features=["colored"]}
chrono="*"


