[package]
name = "VARF"
version = "0.1.0"
authors = ["DSOM"]
edition = "2018"

[dependencies]
log="*"
intrusive-collections = "*"
logos = "0.10.0-rc2"
enum-as-inner = "*"
indexmap = "*"
bytecount = "*"
ahash = "*"
smallvec = "*"
lazy_static = "*"

[dependencies.annotate-snippets]
version = "*"
features = ["ansi_term"]

[dependencies.bumpalo]
version = "*"
features=['collections']

#Logging for tests
[dev-dependencies]
fern={version="*",features=["colored"]}
chrono="*"
jemallocator-global = "*"
