[package]
name = "verilogae_ffi"
version = "0.9.0-beta5"
authors = ["DSPOM"]
edition = "2021"
license = "GPL-3.0"

links = "verilogae"

[lib]
doctest = false


[dependencies]

verilogae = { version = "0.9.0-beta5", path = "../verilogae", optional=true}

[dev-dependencies]

sourcegen = {version = "0.0.0", path="../sourcegen"}
xshell = "0.1"


[features]

default = ["build"]
build = ["verilogae"]



