[workspace]

members = [
    "ast",
    "ast_lowering",

    "constants",

    "codegen_llvm",

    "data_structures",

    "diagnostics",

    "hir",
    "ir",
    "middle",

    "macros",

    "parser",
    "preprocessor",

    "session",

    "pass",
    "targets",

    "linker",
    "lld"
]