[package]
name = "hir"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2018"
repository= "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler frontend for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../README.md"

[badges]
maintenance = { status = "actively-developed" }


[dependencies]

ast = {version = "0.0.0", path = "../ast"}
constants = {version = "0.0.0", path = "../constants" }
data-structures = {version = "0.0.0", path = "../data_structures" }
diagnostics = {version="0.0.0", path="../diagnostics"}
ir = {version = "0.0.0", path = "../ir"}

middle = {version="0.0.0", path="../middle"}
# session = {version = "0.0.0", path = "../session"}


match_any = "1.0.1"

tracing = "0.1.26"
thiserror = "1.0.26"
enum_dispatch = "0.3.7"
derive_more = "0.99.16"
enumset = "1.0.7"
