[package]
name = "xtask"
version = "0.1.0"
publish = false
license = "GPL-3.0"
edition = "2021"
rust-version = "1.56"

[dependencies]
anyhow = "1.0"
xshell = "0.1"
xflags = "0.2"
sha2 = "0.10"
base32 = "0.4"
# Avoid adding more dependencies to this crate
