[package]
name = "xtask"
version = "0.1.0"
publish = false
license = "GPL-3.0"
edition = "2021"
rust-version = "1.56"

[dependencies]
anyhow = "1.0"
xshell = "0.2"
xflags = "0.3"
md5 = "0.7"
base_n = {version="1",path = "../lib/base_n"}
# Avoid adding more dependencies to this crate
