[package]
name = "mir"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
license="GPL-3.0"

[lib]
doctest = false


[dependencies]
stdx = {version = "0.0.0", path = "../stdx" }
cranelift-entity = "0.80"
lasso = {version = "0.6", features = ["ahash"]}

[dev-dependencies]
expect-test = "1.1"
proc-macro2 = "1.0"
quote = "1.0"
sourcegen = {version = "0.0.0",path ="../sourcegen"}
