[package]
name = "openvaf-driver"
version = "23.5.0"
authors = ["DSPOM"]
edition = "2021"
license = "GPL-3.0"

[[bin]]
name = "openvaf"
path = "src/main.rs"

[dependencies]

openvaf = { version = "0.1.2", path = "../openvaf" }

clap = "4.2"
directories-next = "2"
path-absolutize = "3.1.0"
anyhow = "1"
termcolor = "1.2"
camino = "1.1.4"
env_logger = "0.10.0"
log = "0.4.17"
backtrace-ext = "0.2.1"
backtrace = "0.3.67"

mimalloc = { version = "*", default-features = false}
