[package]
name = "osdi"
version = "0.1.0"
authors = ["DSPOM"]
edition = "2018"
repository= "https://gitlab.com/DSPOM/osdi"
description = "The offical implimentation of the OSDI Model-Info-Store"
license="BSD+Patent"
readme="../README.md"

[badges]
maintenance = { status = "actively-developed" }


[dependencies]
parking_lot = "0.11"
semver = {version="0.10",features=["serde"]}
index_vec = "0.1"
serde = {version = "1.0", features = ["derive"]}
once_cell = "1.4"
bincode = "1.3"
cfg-if = "0.1"

bitflags = "1.2"
libloading = {version = "0.6", optional = true}
linkme =  {version = "0.2", optional = true}

osdi-types = {version = "0.1", path = "../osdi_types", features = ["serialize"]}
thiserror = "1.0"

[features]

default = ["simulator"]
simulator = ["libloading"]


[package.metadata.docs.rs]
rustdoc-args = [
    "--html-in-header",
    ".cargo/registry/src/github.com-1ecc6299db9ec823/katex-doc-0.1.0/katex.html",
]
