[package]
name = "osdic-codegen"
version = "0.1.0"
authors = ["DSPOM"]
edition = "2021"
repository = "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler frontend for VerilogA aimed predominently at compact modelling"
license = "GPL-3.0"
readme = "../README.md"

[badges]

maintenance = { status = "actively-developed" }


[dependencies]

data-structures = { version = "0.0.0", path = "../../crates/data_structures" }
session = { version = "0.0.0", path = "../../crates/session" }
diagnostics = { version = "0.0.0", path = "../../crates/diagnostics" }
middle = { version = "0.0.0", path = "../../crates/middle" }
codegen-llvm = { version = "0.0.0", path = "../../crates/codegen_llvm" }
linker = { version = "0.0.0", path = "../../crates/linker" }


osdic-target = { version = "0.1.0", path = "../targets" }
osdic-middle = { version = "0.1.0", path = "../middle"}

anyhow = "1.0"
tracing = "0.1"
itertools = "0.10"
target-lexicon = "0.12"
