[package]
name = "osdic-codegen"
version = "0.1.0"
authors = ["DSPOM"]
edition = "2018"
repository = "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler frontend for VerilogA aimed predominently at compact modelling"
license = "GPL-3.0"
readme = "../README.md"

[badges]

maintenance = { status = "actively-developed" }


[dependencies]

openvaf-data-structures = { version = "0.8.0", path = "../../compiler_lib/data_structures" }
openvaf-session = { version = "0.8.0", path = "../../compiler_lib/session" }
openvaf-diagnostics = { version = "0.8.0", path = "../../compiler_lib/diagnostics" }
openvaf-middle = { version = "0.8.0", path = "../../compiler_lib/middle" }
openvaf-codegen-llvm = { version = "0.8.0", path = "../../compiler_lib/codegen_llvm" }


osdic-target = { version = "0.1.0", path = "../targets" }
osdic-linker = { version = "0.1.0", path = "../linker" }
osdic-middle = { version = "0.1.0", path = "../middle"}

anyhow = "1.0"
tracing = "0.1"
itertools = "0.10"
target-lexicon = "0.12"
