[package]
name = "parser"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
repository= "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler frontend for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../README.md"

[badges]
maintenance = { status = "actively-developed" }


[dependencies]

# Error reporting
tracing = "0.1.26"
thiserror = "1.0.26"

data-structures = {version = "0.0.0", path = "../data_structures" }
drop_bomb = "0.1.5"
derive_more = "0.99.16"
