[package]
name = "preprocessor"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
repository= "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler framework for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../README.md"

[badges]
maintenance = { status = "actively-developed" }


[dependencies]

derive_more = "0.99.16"
logos = "0.12.0"
tracing = "0.1.20"

vfs = {version = "0.0.0", path = "../vfs" }
data-structures = {version = "0.0.0", path = "../data_structures" }

[dependencies.annotate-snippets]
version = "0.9.1"
features = ["color"]
