[package]
name = "openvaf-preprocessor"
version = "0.7.0"
authors = ["DSPOM"]
edition = "2018"
repository= "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler frontend for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../README.md"


[badges]
maintenance = { status = "actively-developed" }


[dependencies]

log="0.4"
thiserror = "1.0"
logos = "0.11"
more-asserts = "0.2"

openvaf-data-structures = {version = "0.7.0", path = "../data_structures" }
openvaf-diagnostics = {version = "0.7.0", path = "../diagnostics"}

openvaf-parser = {version = "0.7.0", path = "../parser"}
openvaf-session = {version = "0.7.0", path = "../session"}

[dev-dependencies]
openvaf-test = {version = "0.7.0", path = "../test"}
