[package]
name = "openvaf-transformations"
version = "0.7.1"
authors = ["DSPOM"]
edition = "2018"
repository= "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler frontend for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../README.md"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]

openvaf-data-structures = {version = "0.7.1", path = "../data_structures" }
openvaf-session = {version = "0.7.1", path = "../session"}
openvaf-diagnostics = {version = "0.7.1", path = "../diagnostics"}

openvaf-middle = {version = "0.7.1", path = "../middle" }
openvaf-ir = {version = "0.7.1", path = "../ir"}


serde = {version = "1.0", features = ["derive"], optional = true}
tracing = "0.1"


[features]

default = []
serde_dump  = ["serde","openvaf-middle/serde_dump"]

