[package]
name = "hir_def"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
repository= "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler frontend for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../README.md"

[badges]
maintenance = { status = "actively-developed" }

[lib]
doctest = false

[dependencies]

# constants = {version = "0.0.0", path = "../constants" }

# middle = {version="0.0.0", path="../middle"}
# session = {version = "0.0.0", path = "../session"}

data-structures = {version = "0.0.0", path = "../data_structures" }
basedb = {version = "0.0.0", path = "../basedb" }
syntax = {version = "0.0.0", path = "../syntax"}

salsa = "0.17.0-pre.2"
tracing = "0.1.26"
derive_more = "0.99.16"

[dev-dependencies]

sourcegen = {version ="0.0.0", path ="../sourcegen"}

