[package]
name = "hir_def"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
repository= "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler frontend for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../README.md"

[badges]
maintenance = { status = "actively-developed" }

[lib]
doctest = false

[dependencies]

# data-structures = {version = "0.0.0", path = "../data_structures" }
basedb = {version = "0.0.0", path = "../basedb" }
syntax = {version = "0.0.0", path = "../syntax"}
stdx = {version = "0.0.0", path = "../stdx" }
arena = {version = "0.0.0", path = "../arena" }
# bitset = {version = "0.0.0", path = "../bitset" }

salsa = "0.17.0-pre.2"
# tracing = "0.1.26"
once_cell = "1.3"

# Netype Wrappers
text-size = "1.1"
typed-index-collections = "3.0"

# Performant collections
ahash = "0.7"
lasso = {version = "0.6", features = ["ahash"]}

[dev-dependencies]

sourcegen = {version ="0.0.0", path ="../sourcegen"}
parking_lot = "0.11"
expect-test = "1.1"
proc-macro2 = "1.0"
quote = "1.0"
indexmap = "1.6"
