[package]
name = "hir_lower"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
license = "GPL-3.0"

[lib]
doctest = false


[dependencies]
stdx = { version = "0.0.0", path = "../stdx" }
cfg = { version = "0.0.0", path = "../cfg" }
hir_ty = { version = "0.0.0", path = "../hir_ty" }
hir_def = { version = "0.0.0", path = "../hir_def" }
syntax = {version = "0.0.0", path = "../syntax"}
typed_indexmap = {version = "0.0.0", path = "../typed_indexmap"}

ahash = "0.7"
typed-index-collections = "3.0"
indexmap = "1.6"
lasso = {version = "0.6", features = ["ahash"]}

[dev-dependencies]

sourcegen = {version ="0.0.0", path ="../sourcegen"}
parking_lot = "0.11"
expect-test = "1.1"
proc-macro2 = "1.0"
quote = "1.0"
basedb = { version = "0.0.0", path = "../basedb" }
salsa = "0.17.0-pre.2"
