[package]
name = "osdic-hir-lowering"
version = "0.8.0"
authors = ["DSPOM"]
edition = "2018"
repository = "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler frontend for VerilogA aimed predominently at compact modelling"
license = "GPL-3.0"
readme = "../README.md"

[badges]

maintenance = { status = "actively-developed" }


[dependencies]

openvaf-data-structures = { version = "0.8.0", path = "../../compiler_lib/data_structures" }
openvaf-session = { version = "0.8.0", path = "../../compiler_lib/session" }
openvaf-diagnostics = { version = "0.8.0", path = "../../compiler_lib/diagnostics" }
osdic-target = { version = "0.1.0", path = "../targets" }

openvaf-middle = { version = "0.8.0", path = "../../compiler_lib/middle" }
openvaf-ir = { version = "0.8.0", path = "../../compiler_lib/ir" }
openvaf-transformations = { version = "0.8.0", path = "../../compiler_lib/transformations" }
openvaf-hir-lowering = { version = "0.8.0", path = "../../compiler_lib/hir_lowering" }
openvaf-hir = { version = "0.8.0", path = "../../compiler_lib/hir" }
openvaf-parser = { version = "0.8.0", path = "../../compiler_lib/parser" }
openvaf-preprocessor = { version = "0.8.0", path = "../../compiler_lib/preprocessor" }
openvaf-ast-lowering = { version = "0.8.0", path = "../../compiler_lib/ast_lowering"}

tracing = "0.1"
