[package]
name = "openvaf-constants"
version = "0.7.0"
authors = ["DSPOM"]
edition = "2018"
repository= "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler framework for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../README.md"

[badges]
maintenance = { status = "actively-developed" }


[dependencies]

more-asserts = "0.2"
log = "0.4"
linkme = "0.2"

openvaf-session= {version = "0.7.0", path = "../session"}
openvaf-diagnostics = {version = "0.7.0", path = "../diagnostics"}
once_cell = "1.4"

[dependencies.bytecount]
version = "0.6"
features = ["runtime-dispatch-simd"]


