[package]
name = "constants"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
repository= "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler framework for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../README.md"

[badges]
maintenance = { status = "actively-developed" }


[dependencies]

more-asserts = "0.2.1"
log = "0.4.14"
linkme = "0.2.6"

#session= {version = "0.0.0", path = "../session"}
diagnostics = {version = "0.0.0", path = "../diagnostics"}
once_cell = "1.8.0"

[dependencies.bytecount]
version = "0.6.2"
features = ["runtime-dispatch-simd"]


