[package]
name = "pass"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
repository= "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler frontend for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../README.md"

[lib]
doctest = false
[badges]
maintenance = { status = "actively-developed" }

[dependencies]

data-structures = {version = "0.0.0", path = "../data_structures" }
# session = {version = "0.0.0", path = "../session"}
diagnostics = {version = "0.0.0", path = "../diagnostics"}

middle = {version = "0.0.0", path = "../middle" }
ir = {version = "0.0.0", path = "../ir"}

tracing = "0.1.26"
itertools = "0.10.1"


[features]

default = []

