[package]
name = "osdi-types"
version = "0.1.0"
authors = ["DSPOM"]
edition = "2021"
repository= "https://gitlab.com/DSPOM/osdi"
description = "The offical implimentation of the OSDI Model-Info-Store"
license="BSD+Patent"
readme="../README.md"

[badges]
maintenance = { status = "actively-developed" }


[dependencies]
index_vec = "0.1.2"
serde = { version = "1.0.126", features = ["derive"], optional = true }
cfg-if = "1.0.0"
parking_lot = "0.11.1"
num-complex = "0.4.0"


[features]

default = []
serialize = ["serde","num-complex/serde"]
