[package]
name = "osdi-types"
version = "0.1.0"
authors = ["DSPOM"]
edition = "2018"
repository= "https://gitlab.com/DSPOM/osdi"
description = "The offical implimentation of the OSDI Model-Info-Store"
license="BSD+Patent"
readme="../README.md"

[badges]
maintenance = { status = "actively-developed" }


[dependencies]
index_vec = "0.1"
serde = {version = "1.0", features = ["derive"], optional = true}
cfg-if = "0.1"
parking_lot = "0.11"
num-complex = "0.4"


[features]

default = []
serialize = ["serde"]