[package]
name = "osdic-target"
version = "0.1.0"
authors = ["DSPOM"]
edition = "2018"
repository= "https://gitlab.com/DSPOM/osdi"
description = "A compiler frontend for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../README.md"

[badges]

maintenance = { status = "actively-developed" }


[dependencies]

openvaf-targets = {version = "0.8.0", path = "../../compiler_lib/targets" }
openvaf-data-structures = {version = "0.8.0", path = "../../compiler_lib/data_structures"}
osdi-types = {version="0.1.0", path = "../../osdi/osdi_types"}
tracing = "0.1"
thiserror = "1.0"