[package]
name = "vfs"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
doctest = false

[dependencies]

data-structures = {path="../data_structures",version="0.0.0"}

