[package]
name = "osdic-middle"
version = "0.1.0"
authors = ["DSPOM"]
edition = "2021"
repository = "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler frontend for VerilogA aimed predominently at compact modelling"
license = "GPL-3.0"
readme = "../README.md"

[badges]

maintenance = { status = "actively-developed" }


[dependencies]

data-structures = { version = "0.0.0", path = "../../crates/data_structures" }
session = { version = "0.0.0", path = "../../crates/session" }
diagnostics = { version = "0.0.0", path = "../../crates/diagnostics" }
osdic-target = { version = "0.1.0", path = "../targets" }

middle = { version = "0.0.0", path = "../../crates/middle" }
ir = { version = "0.0.0", path = "../../crates/ir" }
pass = { version = "0.0.0", path = "../../crates/pass" }
hir = { version = "0.0.0", path = "../../crates/hir" }
parser = { version = "0.0.0", path = "../../crates/parser_old" }
preprocessor = { version = "0.0.0", path = "../../crates/preprocessor" }
ast-lowering = { version = "0.0.0", path = "../../crates/ast_lowering"}

tracing = "0.1"
itertools = "0.10"
