[package]
name = "middle"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2018"
repository= "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler frontend for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../README.md"

[badges]

maintenance = { status = "actively-developed" }


[dependencies]

data-structures = {version = "0.0.0", path = "../data_structures" }
ir = {version = "0.0.0", path = "../ir"}
# session = {version = "0.0.0", path = "../session"}
diagnostics = {version = "0.0.0", path = "../diagnostics" }
macros = {version =" 0.0.0", path="../macros"}

osdi-types = {version = "0.1", path="../../osdi/osdi_types"}
log = "0.4.14"
tracing = "0.1.26"
rustc-ap-graphviz = { version = "662.0.0", optional = true }
enum-map = "1.1.1"
thiserror = "1.0.26"
itertools = "0.10.1"
match_any = "1.0.1"
enum_dispatch = "0.3.7"
derive_more = "0.99.16"


[features]

default = []
graphviz = ["rustc-ap-graphviz"]
