[package]
name = "openvaf-data-structures"
version = "0.7.0"
authors = ["DSPOM"]
edition = "2018"
repository= "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler framework for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../../README.md"

[badges]
maintenance = { status = "actively-developed" }


[dependencies]


more-asserts = "0.2"

ahash = "0.4"
parking_lot = "0.11"
once_cell = "1.4"

fixedbitset = "0.3"
index_vec = "0.1"

cfg-if = "0.1"


[features]

default = []


threading = []

nightly = ["parking_lot/nightly"]