name: Rust CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-linux:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: base-devel

    - name: Install MSYS2 toolchain
      run: |
        pacman -Syu --noconfirm
        pacman -S --needed --noconfirm mingw-w64-ucrt-x86_64-toolchain
        pacboy -S --needed --noconfirm rust:p clang:p llvm:p cc:p

    - name: Build with Cargo
      run: cargo build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y clang llvm-18

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run cargo machete
      run: cargo machete

    - name: Check code formatting
      run: |
        cargo fmt -- --check
        if [ $? -ne 0 ]; then
          echo "Code is not formatted. Please run 'cargo fmt'."
          exit 1
        fi

    - name: Run tests
      run: cargo test --release
