name: Rust CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-linux:
  msys2-build-test: #cargo test doesn't necessarily build the exec we want
    strategy:
      matrix:
        sys: [MINGW64, UCRT64, CLANG64]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: base-devel git
        pacboy: >-
          clang:p
          llvm18:p
    - name: Run cargo 
      shell: msys2 {0}
      run: cargo build --release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y clang llvm-18

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run cargo machete
      run: cargo machete

    - name: Check code formatting
      run: |
        cargo fmt -- --check
        if [ $? -ne 0 ]; then
          echo "Code is not formatted. Please run 'cargo fmt'."
          exit 1
        fi

    - name: Run tests
      run: cargo test --release
