name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run cargo machete
      run: cargo machete

    - name: Check code formatting
      run: |
        cargo fmt -- --check
        if [ $? -ne 0 ]; then
          echo "Code is not formatted. Please run 'cargo fmt'."
          exit 1
        fi

    - name: Run tests
      run: cargo test --release
