name: Rust CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  msys2-build-test: #cargo test doesn't necessarily build the exec we want
    strategy:
      matrix:
        sys: [MINGW64, UCRT64, CLANG64]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: base-devel git
        pacboy: >-
          clang:p
          llvm:p
          rust:p
          cc:p
    - name: Run cargo 
      shell: msys2 {0}
      run: cargo build --release

    - name: Install cargo-machete
      run: cargo install cargo-machete

    - name: Add cargo bin to PATH
      run: echo "${{ github.workspace }}/.cargo/bin" >> $GITHUB_PATH

    - name: Run cargo machete
      run: cargo machete

    - name: Check code formatting
      run: |
        cargo fmt -- --check
        if [ $? -ne 0 ]; then
          echo "Code is not formatted. Please run 'cargo fmt'."
          exit 1
        fi

    - name: Run tests
      run: cargo test --release
